-- Insert Authors
INSERT INTO authors (name, biography) VALUES
('J.K. Rowling', 'British author best known for the Harry Potter series'),
('George R.R. Martin', 'American novelist and short story writer, best known for A Song of Ice and Fire'),
('Stephen King', 'American author of horror, supernatural fiction, suspense, and fantasy novels'),
('Agatha Christie', 'British writer known for her detective novels'),
('J.R.R. Tolkien', 'English writer, poet, philologist, and academic, best known for The Lord of the Rings'),
('Neil Gaiman', 'English author of short fiction, novels, comic books, and films'),
('Dan Brown', 'American author known for his thriller novels'),
('Paulo Coelho', 'Brazilian lyricist and novelist, best known for The Alchemist'),
('Margaret Atwood', 'Canadian poet, novelist, and literary critic'),
('Haruki Murakami', 'Japanese writer, his works are characterized by magical realism'),
('Terry Pratchett', 'English author of fantasy novels, especially Discworld series'),
('Isaac Asimov', 'American writer and professor of biochemistry, known for science fiction works'),
('Jane Austen', 'English novelist known for her romance fiction'),
('Gabriel García Márquez', 'Colombian author known for magical realism'),
('Douglas Adams', 'English author, best known for The Hitchhiker''s Guide to the Galaxy');

-- Insert Categories
INSERT INTO categories (name, description) VALUES
('Fantasy', 'Books involving magic and supernatural phenomena'),
('Mystery', 'Books involving crime solving and detective work'),
('Horror', 'Books intended to frighten, scare, or startle readers'),
('Science Fiction', 'Books based on imagined future scientific or technological advances'),
('Romance', 'Books focusing on romantic relationships'),
('Non-Fiction', 'Books based on facts and real events'),
('Adventure', 'Books about exciting or dangerous journeys'),
('Literary Fiction', 'Character-driven narratives focusing on the human condition'),
('Historical Fiction', 'Fictional stories set in the past'),
('Thriller', 'Books designed to keep readers in suspense'),
('Contemporary Fiction', 'Fiction set in modern times'),
('Classic Literature', 'Books that have stood the test of time'),
('Young Adult', 'Books targeting teenage readers'),
('Biography', 'Books about real people''s lives'),
('Poetry', 'Literary work in verse');

-- Insert Books
INSERT INTO books (title, description, isbn, publication_year, img_url, author_id) VALUES
('Harry Potter and the Philosopher''s Stone', 'The first book in the Harry Potter series', '9780747532743', 1997, 'https://example.com/hp1.jpg', 1),
('Harry Potter and the Chamber of Secrets', 'The second book in the Harry Potter series', '9780747538486', 1998, 'https://example.com/hp2.jpg', 1),
('A Game of Thrones', 'The first book in A Song of Ice and Fire series', '9780553103540', 1996, 'https://example.com/got1.jpg', 2),
('The Shining', 'A horror novel about a family trapped in a haunted hotel', '9780385121675', 1977, 'https://example.com/shining.jpg', 3),
('Murder on the Orient Express', 'A detective novel featuring Hercule Poirot', '9780007119318', 1934, 'https://example.com/orient.jpg', 4),
('The Hobbit', 'A fantasy novel about Bilbo Baggins', '9780547928227', 1937, 'https://example.com/hobbit.jpg', 5),
('The Fellowship of the Ring', 'The first part of The Lord of the Rings', '9780547928210', 1954, 'https://example.com/lotr1.jpg', 5),
('A Clash of Kings', 'The second book in A Song of Ice and Fire series', '9780553108033', 1998, 'https://example.com/got2.jpg', 2),
('IT', 'A horror novel about a shape-shifting evil', '9780450411435', 1986, 'https://example.com/it.jpg', 3),
('Death on the Nile', 'A detective novel featuring Hercule Poirot', '9780062073556', 1937, 'https://example.com/nile.jpg', 4),
('American Gods', 'A novel about old and new gods in modern America', '9780380789030', 2001, 'https://example.com/ag.jpg', 6),
('The Da Vinci Code', 'A mystery thriller involving religious conspiracies', '9780385504201', 2003, 'https://example.com/dvc.jpg', 7),
('The Alchemist', 'A philosophical novel about following one''s dreams', '9780062315007', 1988, 'https://example.com/alchemist.jpg', 8),
('The Handmaid''s Tale', 'A dystopian novel about women''s rights', '9780385490818', 1985, 'https://example.com/handmaid.jpg', 9),
('1Q84', 'A novel about parallel existences', '9780307593313', 2009, 'https://example.com/1q84.jpg', 10),
('Good Omens', 'A comedy about the apocalypse', '9780060853976', 1990, 'https://example.com/omens.jpg', 6),
('Foundation', 'A science fiction novel about the decline and rebirth of civilization', '9780553293357', 1951, 'https://example.com/foundation.jpg', 12),
('Pride and Prejudice', 'A romantic novel about societal expectations', '9780141439518', 1813, 'https://example.com/pride.jpg', 13),
('One Hundred Years of Solitude', 'A multi-generational story of the Buendía family', '9780060883287', 1967, 'https://example.com/solitude.jpg', 14),
('The Hitchhiker''s Guide to the Galaxy', 'A comedy science fiction series', '9780345391803', 1979, 'https://example.com/hitchhiker.jpg', 15),
('Kafka on the Shore', 'A metaphysical journey of a teenage boy', '9781400079278', 2002, 'https://example.com/kafka.jpg', 10),
('The Color of Magic', 'The first Discworld novel', '9780062225672', 1983, 'https://example.com/color.jpg', 11),
('Angels & Demons', 'A thriller involving CERN and the Vatican', '9781416524797', 2000, 'https://example.com/angels.jpg', 7),
('The Blind Assassin', 'A novel within a novel', '9780385720953', 2000, 'https://example.com/assassin.jpg', 9),
('I, Robot', 'A collection of robot stories', '9780553294385', 1950, 'https://example.com/robot.jpg', 12);

-- Link Books to Categories (book_categories)
INSERT INTO book_categories (book_id, category_id) VALUES
(1, 1), (2, 1), (3, 1), (3, 7), (4, 3), (5, 2), (6, 1), (6, 7), (7, 1), (7, 7),
(8, 1), (8, 7), (9, 3), (10, 2),
(11, 1), (11, 8), (12, 2), (12, 10), (13, 8), (13, 11), (14, 4), (14, 8), (15, 8), (15, 11),
(16, 1), (16, 11), (17, 4), (18, 5), (18, 12), (19, 8), (19, 12), (20, 4), (20, 11),
(21, 8), (21, 11), (22, 1), (22, 11), (23, 2), (23, 10), (24, 8), (24, 11), (25, 4);

-- Insert Members
INSERT INTO members (first_name, last_name, email, phone) VALUES
('John', 'Doe', 'john.doe@example.com', '1234567890'),
('Jane', 'Smith', 'jane.smith@example.com', '2345678901'),
('Robert', 'Johnson', 'robert.j@example.com', '3456789012'),
('Mary', 'Williams', 'mary.w@example.com', '4567890123'),
('Michael', 'Brown', 'michael.b@example.com', '5678901234'),
('Sarah', 'Davis', 'sarah.d@example.com', '6789012345'),
('David', 'Miller', 'david.m@example.com', '7890123456'),
('Lisa', 'Wilson', 'lisa.w@example.com', '8901234567'),
('James', 'Moore', 'james.m@example.com', '9012345678'),
('Emily', 'Taylor', 'emily.t@example.com', '0123456789'),
('William', 'Anderson', 'william.a@example.com', '1122334455'),
('Emma', 'Thomas', 'emma.t@example.com', '2233445566'),
('Oliver', 'Jackson', 'oliver.j@example.com', '3344556677'),
('Sophia', 'White', 'sophia.w@example.com', '4455667788'),
('Lucas', 'Harris', 'lucas.h@example.com', '5566778899'),
('Ava', 'Martin', 'ava.m@example.com', '6677889900'),
('Mason', 'Thompson', 'mason.t@example.com', '7788990011'),
('Isabella', 'Garcia', 'isabella.g@example.com', '8899001122'),
('Ethan', 'Martinez', 'ethan.m@example.com', '9900112233'),
('Mia', 'Robinson', 'mia.r@example.com', '0011223344');

-- Insert Borrowed Books (some current, some returned)
INSERT INTO borrowed_books (book_id, member_id, borrow_date, due_date, return_date, status) VALUES
(1, 1, CURRENT_TIMESTAMP - INTERVAL '10 days', CURRENT_TIMESTAMP + INTERVAL '4 days', NULL, 'BORROWED'),
(3, 2, CURRENT_TIMESTAMP - INTERVAL '5 days', CURRENT_TIMESTAMP + INTERVAL '9 days', NULL, 'BORROWED'),
(5, 3, CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP + INTERVAL '12 days', NULL, 'BORROWED'),
(7, 4, CURRENT_TIMESTAMP - INTERVAL '15 days', CURRENT_TIMESTAMP - INTERVAL '1 day', NULL, 'BORROWED'),
(9, 5, CURRENT_TIMESTAMP - INTERVAL '20 days', CURRENT_TIMESTAMP - INTERVAL '6 days', NULL, 'BORROWED'),
(11, 11, CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP + INTERVAL '11 days', NULL, 'BORROWED'),
(13, 12, CURRENT_TIMESTAMP - INTERVAL '7 days', CURRENT_TIMESTAMP + INTERVAL '7 days', NULL, 'BORROWED'),
(15, 13, CURRENT_TIMESTAMP - INTERVAL '25 days', CURRENT_TIMESTAMP - INTERVAL '11 days', NULL, 'BORROWED'),
(17, 14, CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP + INTERVAL '13 days', NULL, 'BORROWED'),
(19, 15, CURRENT_TIMESTAMP - INTERVAL '18 days', CURRENT_TIMESTAMP - INTERVAL '4 days', NULL, 'BORROWED'),
(2, 1, CURRENT_TIMESTAMP - INTERVAL '60 days', CURRENT_TIMESTAMP - INTERVAL '46 days', CURRENT_TIMESTAMP - INTERVAL '45 days', 'RETURNED'),
(4, 2, CURRENT_TIMESTAMP - INTERVAL '45 days', CURRENT_TIMESTAMP - INTERVAL '31 days', CURRENT_TIMESTAMP - INTERVAL '32 days', 'RETURNED'),
(6, 3, CURRENT_TIMESTAMP - INTERVAL '30 days', CURRENT_TIMESTAMP - INTERVAL '16 days', CURRENT_TIMESTAMP - INTERVAL '18 days', 'RETURNED'),
(8, 4, CURRENT_TIMESTAMP - INTERVAL '25 days', CURRENT_TIMESTAMP - INTERVAL '11 days', CURRENT_TIMESTAMP - INTERVAL '10 days', 'RETURNED'),
(10, 5, CURRENT_TIMESTAMP - INTERVAL '15 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 days', 'RETURNED'),
(12, 6, CURRENT_TIMESTAMP - INTERVAL '90 days', CURRENT_TIMESTAMP - INTERVAL '76 days', CURRENT_TIMESTAMP - INTERVAL '77 days', 'RETURNED'),
(14, 7, CURRENT_TIMESTAMP - INTERVAL '75 days', CURRENT_TIMESTAMP - INTERVAL '61 days', CURRENT_TIMESTAMP - INTERVAL '60 days', 'RETURNED'),
(16, 8, CURRENT_TIMESTAMP - INTERVAL '60 days', CURRENT_TIMESTAMP - INTERVAL '46 days', CURRENT_TIMESTAMP - INTERVAL '47 days', 'RETURNED'),
(18, 9, CURRENT_TIMESTAMP - INTERVAL '45 days', CURRENT_TIMESTAMP - INTERVAL '31 days', CURRENT_TIMESTAMP - INTERVAL '30 days', 'RETURNED'),
(20, 10, CURRENT_TIMESTAMP - INTERVAL '30 days', CURRENT_TIMESTAMP - INTERVAL '16 days', CURRENT_TIMESTAMP - INTERVAL '15 days', 'RETURNED'),
(21, 16, CURRENT_TIMESTAMP - INTERVAL '120 days', CURRENT_TIMESTAMP - INTERVAL '106 days', CURRENT_TIMESTAMP - INTERVAL '105 days', 'RETURNED'),
(22, 17, CURRENT_TIMESTAMP - INTERVAL '100 days', CURRENT_TIMESTAMP - INTERVAL '86 days', CURRENT_TIMESTAMP - INTERVAL '87 days', 'RETURNED'),
(23, 18, CURRENT_TIMESTAMP - INTERVAL '80 days', CURRENT_TIMESTAMP - INTERVAL '66 days', CURRENT_TIMESTAMP - INTERVAL '65 days', 'RETURNED'),
(24, 19, CURRENT_TIMESTAMP - INTERVAL '70 days', CURRENT_TIMESTAMP - INTERVAL '56 days', CURRENT_TIMESTAMP - INTERVAL '54 days', 'RETURNED'),
(25, 20, CURRENT_TIMESTAMP - INTERVAL '50 days', CURRENT_TIMESTAMP - INTERVAL '36 days', CURRENT_TIMESTAMP - INTERVAL '35 days', 'RETURNED'),
(1, 11, CURRENT_TIMESTAMP - INTERVAL '150 days', CURRENT_TIMESTAMP - INTERVAL '136 days', CURRENT_TIMESTAMP - INTERVAL '135 days', 'RETURNED'),
(3, 12, CURRENT_TIMESTAMP - INTERVAL '140 days', CURRENT_TIMESTAMP - INTERVAL '126 days', CURRENT_TIMESTAMP - INTERVAL '125 days', 'RETURNED'),
(5, 13, CURRENT_TIMESTAMP - INTERVAL '130 days', CURRENT_TIMESTAMP - INTERVAL '116 days', CURRENT_TIMESTAMP - INTERVAL '115 days', 'RETURNED'),
(7, 14, CURRENT_TIMESTAMP - INTERVAL '120 days', CURRENT_TIMESTAMP - INTERVAL '106 days', CURRENT_TIMESTAMP - INTERVAL '105 days', 'RETURNED'),
(9, 15, CURRENT_TIMESTAMP - INTERVAL '110 days', CURRENT_TIMESTAMP - INTERVAL '96 days', CURRENT_TIMESTAMP - INTERVAL '95 days', 'RETURNED'); 